# Generated by Django 5.0.4 on 2024-05-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0007_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
